e_comerce:
  outputs:
    dev:
      dataset: bronze
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/rianf/keys/e-comerce-dbt-b0f121eb7608.json
      location: US
      method: service-account
      priority: interactive
      project: e-comerce-dbt
      threads: 4
      type: bigquery
  target: dev
news_rag:
  outputs:
    dev:
      dbname: neondb
      host: ep-wild-cake-ac1t6ko1-pooler.sa-east-1.aws.neon.tech
      pass: npg_PIdaifgxD49O
      port: 5432
      schema: stage
      threads: 4
      type: postgres
      user: neondb_owner
  target: dev
projeto_vendas:
  outputs:
    dev:
      dataset: silver
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/rianf/keys/treino-479018-ba207d6d879a.json
      location: US
      method: service-account
      priority: interactive
      project: treino-479018
      threads: 4
      type: bigquery
  target: dev
